import Head from 'next/head'
import { gql } from '@apollo/client';

import client from '../lib/apollo';

const Home = ({ homepage }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {homepage.attributes.content}
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const { data: homepageRes } = await client.query({
    query: gql`
      query getHomepage {
        homepage {
          data {
            attributes {
              content
            }
          }
        }
      }
    `
  });

  return {
    props: {
      homepage: homepageRes.homepage.data
    },
    revalidate: 1,
  }
}

export default Home;